#!/usr/bin/env python3
"""Parity check: canonical skill names (skills/*/SKILL.md) vs the ports
that still carry hand-maintained content.

Usage: python3 scripts/check_parity.py [LIB_ROOT]
LIB_ROOT defaults to the repo root (the parent of this scripts/ dir).

Port shapes (owner decision 2026-09-13, issue #11):
  - gemini: retired. No surface here — ports/gemini/ carries only a README
    pointer to the paid-tier Gemini CLI reading skills/ natively.
  - cursor: not per-skill parity. Cursor reads skills/ natively; the port
    carries only what SKILL.md cannot express (always-on floor + two
    glob-scoped rules). Checked by exact file set, not skill coverage.
  - antigravity, agents-md: generated by scripts/gen-ports.py from
    skills/*/SKILL.md, so `gen-ports.py --check` is the parity check for
    both (drift + a uniqueness check) — a stronger guarantee than
    presence alone, so neither surface is duplicated here.
  - skills-local: a deliberate compact-variant subset, not full parity;
    its gaps are tracked in scripts/parity-allow.txt (#10).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _lib

# The exact file set ports/cursor/ must carry: the always-on floor plus the
# two glob-scoped rules SKILL.md cannot express (Cursor reads skills/
# natively for everything else).
CURSOR_FILES = {"baseline.mdc", "testing.mdc", "frontend-design.mdc"}


def present_stems(dir_path: Path, pattern: str) -> set:
    """Stems (or, for a SKILL.md match, the parent directory name) of every
    file under dir_path matching pattern."""
    present = set()
    if not dir_path.is_dir():
        return present
    for f in dir_path.glob(pattern):
        stem = f.parent.name if f.name == "SKILL.md" else f.stem
        present.add(stem)
    return present


def check_cursor_shape(lib: Path) -> list:
    """Cursor carries no per-skill parity. Assert ports/cursor/ contains
    exactly CURSOR_FILES — nothing missing, nothing left over."""
    cursor_dir = lib / "ports" / "cursor"
    if not cursor_dir.is_dir():
        return [f"{cursor_dir} does not exist"]
    actual = {f.name for f in cursor_dir.glob("*.mdc")}
    errors = []
    missing = CURSOR_FILES - actual
    extra = actual - CURSOR_FILES
    if missing:
        errors.append(f"missing required file(s): {', '.join(sorted(missing))}")
    if extra:
        errors.append(f"unexpected file(s): {', '.join(sorted(extra))}")
    return errors


def load_allowlist(lib: Path) -> set:
    allow_file = lib / "scripts" / "parity-allow.txt"
    entries = set()
    if not allow_file.is_file():
        return entries
    for line in allow_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        surface, skill = line.split(":", 1)
        entries.add((surface.strip(), skill.strip()))
    return entries


def main() -> int:
    default_lib = Path(__file__).resolve().parent.parent
    lib = Path(sys.argv[1]) if len(sys.argv) > 1 else default_lib
    canonical = sorted(_lib.skill_names(lib, "skills"))
    if not canonical:
        print(f"FAIL: 0 canonical skills found under {lib / 'skills'} — wrong LIB_ROOT?")
        return 1
    allow = load_allowlist(lib)

    # Per-skill parity surfaces that are not otherwise checked.
    surface_globs = {
        "skills-local": (lib / "skills-local", "*/SKILL.md"),
    }
    surfaces = {
        surface: present_stems(dir_path, pattern)
        for surface, (dir_path, pattern) in surface_globs.items()
    }

    failed = False
    print(f"Canonical skills: {len(canonical)}")
    for surface, present in surfaces.items():
        missing = [s for s in canonical if s not in present]
        allowed_missing = [s for s in missing if (surface, s) in allow]
        real_missing = [s for s in missing if (surface, s) not in allow]
        if not missing:
            print(f"[{surface}] OK — all {len(canonical)} skills present")
            continue
        if allowed_missing:
            print(f"[{surface}] allowlisted gaps: {', '.join(allowed_missing)}")
        if real_missing:
            failed = True
            print(f"[{surface}] MISSING: {', '.join(real_missing)}")
        elif not allowed_missing:
            print(f"[{surface}] OK — all {len(canonical)} skills present")

    # Cursor: shape check, not per-skill parity.
    cursor_errors = check_cursor_shape(lib)
    if cursor_errors:
        failed = True
        print(f"[cursor] FAIL: {'; '.join(cursor_errors)}")
    else:
        print(f"[cursor] OK — exactly {', '.join(sorted(CURSOR_FILES))}")

    if failed:
        print("\nParity check FAILED — see MISSING/FAIL lines above.")
        return 1
    print("\nParity check passed (allowlisted gaps, if any, are listed above).")
    print("(antigravity and agents-md parity: see scripts/gen-ports.py --check)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
